name: client
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <=3.0.5'


dependencies:
  http: ^1.1.0
  protobuf: ^3.0.0
  tart:
    path: ../../tart/

dev_dependencies:
  lints: ^2.1.1
