FROM golang as builder

ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0

COPY . .
RUN cd protoc-gen-tart && go install .

# Note, the Docker images must be built for amd64. If the host machine architecture is not amd64
# you need to cross-compile the binary and move it into /go/bin.
RUN bash -c 'find /go/bin/${GOOS}_${GOARCH}/ -mindepth 1 -maxdepth 1 -exec mv {} /go/bin \;'

FROM scratch

COPY --from=builder /go/bin /

ENTRYPOINT ["/protoc-gen-tart"]
